### ISSUE TITLE
Spectronaut Report Schema

### ISSUE THREAD

**Issue by k2krull** [MannLabs/directlfq#10]
Hi, great work and thanks for sharing!

While playing around, I could not access your preferred export schema for Spectronaut's report files. 
It doesn't seem to exist (404), neither for precursor nor for fragment ion quan.

Is there an update going on?

Best, Karl

**Comment by ammarcsj** [comment]
Hey Karl! :)

thanks a lot for the feedback! This should not happen, how did you try to access the schema? Did you use the the GUI for this?

**Comment by k2krull** [comment]
Sorry for not being clear!
I meant that the download link on the directLFQ github page does not work for me

**Comment by ammarcsj** [comment]
Hi Karl,

thanks for the info! Indeed, the downloads worked under Safari, but not for Firefox and Chrome. I tried to fix it now and it seems to work from my side. Could you check if it also works for you now?

Best
Constantin

**Comment by k2krull** [comment]
Hey Constantin,

yes, it works now! Many thanks!

Best,
Karl

**Comment by ammarcsj** [comment]
great :)
