### ISSUE TITLE
Normalisation values are extremly high

### ISSUE THREAD

**Issue by tomthun** [MannLabs/directlfq#16]
**Describe the bug**

Its not really a bug but i recognized that the values of the normalisation output are overall very high (around 1e15 to 1e16).
I am wondering why this is so. Processing was done with the python version on windows. 

**To Reproduce**

simply run lfq_manager.run_lfq([CustomDf.aq_reformat.txt](https://github.com/MannLabs/directlfq/files/12289431/CustomDf.aq_reformat.txt))

**Comment by ammarcsj** [comment]
Hi! Thank for reaching out :), I checked but cannot reproduce the issue (see attached file). Could you check if this is maybe a decimal point issue? I.e. the numbers behind the comma might be interpreted as integer parts?

Best Constantin

[CustomDf.aq_reformat.tsv.protein_intensities.tsv.zip](https://github.com/MannLabs/directlfq/files/12289632/CustomDf.aq_reformat.tsv.protein_intensities.tsv.zip)

**Comment by tomthun** [comment]
Oh haha yes it is an issue with excel, my bad ^^
