### ISSUE TITLE
Execution time

### ISSUE THREAD

**Issue by tomthun** [MannLabs/directlfq#18]
I  wanted to ask how long the expected execution time for e.g. 1333 Proteins across e.g. 3 replicates is to be expected.

**Comment by ammarcsj** [comment]
Hi Tom,

I would expect it to be shorter than 2 minutes. Most of the time probably going into formatting and writing the table.

Best
Constantin

**Comment by tomthun** [comment]
It was an issue with my pc. After restarting it is in this time range again! Thanks :)
