### ISSUE TITLE
directlfq gui windows won't start (version 0.2.13 and 0.2.14)

### ISSUE THREAD

**Issue by DaliJarboui** [MannLabs/directlfq#22]
First of all, 
thanks a lot for that great tool, very useful.
Unfortunately, the last versions 0.2.13 and 0.2.14 won't start (windows gui) the version 0.2.11 seems to be the last working version, although it comes with a warning (below) that seems not to affect running data.
thanks again for your help
***************
WARNING:param.TextInput: Providing a width-responsive sizing_mode ('stretch_width') and a fixed width is not supported. Converting fixed width to min_width. If you intended the component to be fully width-responsive remove the heightsetting, otherwise change it to min_height. To error on the incorrect specification disable the config.layout_compatibility option.
WARNING:param.TextInput: Providing a width-responsive sizing_mode ('stretch_width') and a fixed width is not supported. Converting fixed width to min_width. If you intended the component to be fully width-responsive remove the heightsetting, otherwise change it to min_height. To error on the incorrect specification disable the config.layout_compatibility option.
WARNING:param.(optional) If you are using MaxQuant evidence.txt or peptides.txt files, you can add the link to the corresponding proteinGroups.txt file (will improve peptide-to-protein mapping): Setting non-parameter attribute default=None using a mechanism intended only for parameters
WARNING:param.: Setting non-parameter attribute default=None using a mechanism intended only for parameters
WARNING:param.TextInput: Providing a width-responsive sizing_mode ('stretch_width') and a fixed width is not supported. Converting fixed width to min_width. If you intended the component to be fully width-responsive remove the heightsetting, otherwise change it to min_height. To error on the incorrect specification disable the config.layout_compatibility option.
WARNING:param.: Setting non-parameter attribute default=None using a mechanism intended only for parameters
WARNING:param.TextInput: Providing a width-responsive sizing_mode ('stretch_width') and a fixed width is not supported. Converting fixed width to min_width. If you intended the component to be fully width-responsive remove the heightsetting, otherwise change it to min_height. To error on the incorrect specification disable the config.layout_compatibility option.
WARNING:param.: Setting non-parameter attribute default=None using a mechanism intended only for parameters
panel\util\warnings.py:26: PanelDeprecationWarning: "Row(..., background='#eaeaea')" is deprecated and will be removed in version 1.3, use "Row(..., styles={'background': '#eaeaea'})" instead.
  warnings.warn(message, category, stacklevel=stacklevel)
Launching server at http://localhost:51170
WARNING:bokeh.core.validation.check:W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Progress(id='p1152', ...)   
*****************

**Comment by ammarcsj** [comment]
Thanks so much for this important info! I will provide a working release with GUI asap and removed the GUI packages from the current one.

Best
Constantin

**Comment by ammarcsj** [comment]
Should be fixed in the new release. Thanks again!
