### ISSUE TITLE
What is the format of the protein list use for normalization

### ISSUE THREAD

**Issue by Lang5991** [MannLabs/directlfq#33]
Dear Mann,
May I know what is the format of the protein list use for normalization?
<img width="611" alt="image" src="https://github.com/MannLabs/directlfq/assets/143386047/d7900f47-ac50-409a-8ecc-bfe69fffe7be">
Thanks

**Comment by ammarcsj** [comment]
Hi, you can just save a list like below as a file, e.g. with a .tsv or .txt ending.

PROTEIN_1
PROTEIN_2
..
PROTEIN_N

**Comment by Lang5991** [comment]
> Hi, you can just save a list like below as a file, e.g. with a .tsv or .txt ending.
> 
> PROTEIN_1 PROTEIN_2 .. PROTEIN_N

PROTEIN_1 means protein name(e.g. GAPDH), gene name(gapdh), or Uniprot_ID (e.g. Q5XJ10)? Thank you for your reply.

**Comment by ammarcsj** [comment]
The uniprot identifier. 

Just to give some context: directLFQ per default uses the protein identifiers of the respective search engine outputs. With the list you specify which of those you want to use for normalization.
