### ISSUE TITLE
test_data/system_tests missing from repo

### ISSUE THREAD

**Issue by sooheon** [MannLabs/directlfq#38]
A lot of tests refer to files in test_data/system_tests, which is missing from master branch.

**Comment by ammarcsj** [comment]
Hi, in the README, there is a section [reproducing-data-analyses-from-the-paper](https://github.com/MannLabs/directlfq?tab=readme-ov-file#reproducing-data-analyses-from-the-paper). There you are instructed how to download these files. Let me know in case there is any problem
