### ISSUE TITLE
Feature request: support DIANN parquet output

### ISSUE THREAD

**Issue by sooheon** [MannLabs/directlfq#45]
Parquet file output is the default starting from 1.9, and is much smaller and more portable. Please let me know if this is a PR welcome type issue

**Comment by ammarcsj** [comment]
Hi, the newest release now has this feature

**Comment by Andre-C-M** [comment]
maybe adding the info in the GUI would help not to miss this feature:
'Provide the path to the DIANN report.tsv output table.'
-->
'Provide the path to the DIANN report.tsv or .report.parquet output table'
